DM_SCHEMA = [
    {
        "name": "second_of_minute",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "second",
        "long_name": "Second of minute",
    },
    {
        "name": "vertical_speed_1",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Vertical speed, 1st sample of second",
    },
    {
        "name": "vertical_speed_2",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Vertical speed, 2nd sample of second",
    },
    {
        "name": "vertical_speed_3",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Vertical speed, 3rd sample of second",
    },
    {
        "name": "vertical_speed_4",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Vertical speed, 4th sample of second",
    },
    {
        "name": "vertical_speed_5",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Vertical speed, 5th sample of second",
    },
    {
        "name": "vertical_speed_6",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Vertical speed, 6th sample of second",
    },
    {
        "name": "horizontal_speed_1",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Horizontal speed, 1st sample of second",
    },
    {
        "name": "horizontal_speed_2",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Horizontal speed, 2nd sample of second",
    },
    {
        "name": "horizontal_speed_3",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Horizontal speed, 3rd sample of second",
    },
    {
        "name": "horizontal_speed_4",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Horizontal speed, 4th sample of second",
    },
    {
        "name": "horizontal_speed_5",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Horizontal speed, 5th sample of second",
    },
    {
        "name": "horizontal_speed_6",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Horizontal speed, 6th sample of second",
    },
    {
        "name": "lla_llb_ratio",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x,
        "units": "1",
        "long_name": "Ratio of LLA to LLB or H+ mode indicator",
    },
    {
        "name": "measured_aperture_potential",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 100.0) - 19.0, 1),
        "units": "V",
        "long_name": "Measured aperture potential",
    },
    {
        "name": "zero_fill",
        "size": 8,
        "type": "bytes",
        "transform": lambda x: x,
        "units": None,
        "long_name": "Zero fill",
    },
]