HEADER_SCHEMA_2 = [
    {
        "name": "spacecraft_id",
        "size": 5,
        "type": "ascii",
        "transform": lambda x: x.strip(),
        "units": None,
        "long_name": "Spacecraft ID",
    },
    {
        "name": "data_file_id",
        "size": 6,
        "type": "ascii",
        "transform": lambda x: x.strip(),
        "units": None,
        "long_name": "Data file ID",
    },
    {
        "name": "year",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x + 1950,
        "units": "year",
        "long_name": "Year",
    },
    {
        "name": "day_of_year",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x,
        "units": "day",
        "long_name": "Day of year",
    },
    {
        "name": "hour",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "hour",
        "long_name": "Hour of day",
    },
    {
        "name": "minute_of_hour",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "minute",
        "long_name": "Minute of hour",
    },
    {
        "name": "geodetic_latitude",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
        "units": "degrees_north",
        "long_name": "Geodetic latitude",
    },
    {
        "name": "geographic_longitude",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees_east",
        "long_name": "Geographic longitude",
    },
    {
        "name": "geomagnetic_latitude_subsat",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
        "units": "degrees",
        "long_name": "Geomagnetic latitude at sub-satellite point",
    },
    {
        "name": "mlt_110km_intercept",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "hours",
        "long_name": "Magnetic local time at 110 km field line intercept",
    },
    {
        "name": "geomagnetic_longitude_subsat",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees",
        "long_name": "Geomagnetic longitude at sub-satellite point",
    },
    {
        "name": "geographic_latitude_subsolar",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
        "units": "degrees_north",
        "long_name": "Geographic latitude of sub-solar point",
    },
    {
        "name": "geographic_longitude_subsolar",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees_east",
        "long_name": "Geographic longitude of sub-solar point",
    },
    {
        "name": "geographic_latitude_110km",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
        "units": "degrees_north",
        "long_name": "Geographic latitude at 110 km altitude on the same magnetic field line as the spacecraft",
    },
    {
        "name": "geographic_longitude_110km",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees_east",
        "long_name": "Geographic longitude at 110 km altitude on the same magnetic field line as the spacecraft",
    },
    {
        "name": "corrected_geomagnetic_latitude_110km",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
        "units": "degrees",
        "long_name": "Corrected geomagnetic latitude at 110 km altitude",
    },
    {
        "name": "corrected_geomagnetic_longitude_110km",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees",
        "long_name": "Corrected geomagnetic longitude at 110 km altitude",
    },
    {
        "name": "invariant_latitude",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees",
        "long_name": "Invariant latitude",
    },
    {
        "name": "altitude_start_minute",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x,
        "units": "nmi",
        "long_name": "Altitude at the start of the minute",
    },
    {
        "name": "altitude_end_minute",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x,
        "units": "nmi",
        "long_name": "Altitude at the end of the minute",
    },
    {
        "name": "model_magnetic_north",
        "size": 4,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 70000.0, 1),
        "units": "nT",
        "long_name": "Northward component of model magnetic field at the satellite",
    },
    {
        "name": "model_magnetic_east",
        "size": 4,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 70000.0, 1),
        "units": "nT",
        "long_name": "Eastward component of model magnetic field at the satellite",
    },
    {
        "name": "model_magnetic_down",
        "size": 4,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 70000.0, 1),
        "units": "nT",
        "long_name": "Downward component of model magnetic field at the satellite",
    },
    {
        "name": "satellite_pos_x",
        "size": 3,
        "type": "uint",
        "transform": lambda x: round((x / 100000.0) - 1.0, 1),
        "units": "1",
        "long_name": "Geographic x-component of satellite position unit vector",
    },
    {
        "name": "satellite_pos_y",
        "size": 3,
        "type": "uint",
        "transform": lambda x: round((x / 100000.0) - 1.0, 1),
        "units": "1",
        "long_name": "Geographic y-component of satellite position unit vector",
    },
    {
        "name": "satellite_pos_z",
        "size": 3,
        "type": "uint",
        "transform": lambda x: round((x / 100000.0) - 1.0, 1),
        "units": "1",
        "long_name": "Geographic z-component of satellite position unit vector",
    },
    {
        "name": "potential_control_flag",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "1",
        "long_name": "Potential control model flag",
    },
    {
        "name": "spacecraft_electron_probe_ground_potential",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x - 10,
        "units": "V",
        "long_name": "Potential difference between spacecraft and electron probe ground",
    },
    {
        "name": "ion_array_electron_probe_ground_potential",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x - 3,
        "units": "V",
        "long_name": "Potential difference between ion array and electron probe ground",
    },
    {
        "name": "repeller_grid_functions",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "1",
        "long_name": "Drift meter repeller grid functions",
    },
    {
        "name": "scintillation_filter_commands",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "1",
        "long_name": "Scintillation meter filter range commands",
    },
    {
        "name": "number_set",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "count",
        "long_name": "Number of outputs for this minute",
    },
]