MP_SCHEMA = [
    {
        "name": "second_of_minute",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "second",
        "long_name": "Second of minute for the set of data",
    },
    {
        "name": "ram_ion_drift_speed",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Ram ion drift speed",
    },
    {
        "name": "o_plus_ion_temperature",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x * 10.0,
        "units": "K",
        "long_name": "O+ ion temperature",
    },
    {
        "name": "h_plus_ion_temperature",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x * 10.0,
        "units": "K",
        "long_name": "H+ ion temperature",
    },
    {
        "name": "o_plus_ion_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "O+ ion density",
    },
    {
        "name": "h_plus_ion_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "H+ ion density",
    },
    {
        "name": "plasma_potential_relative_to_rpa_ground",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 100.0) - 6.0, 1),
        "units": "V",
        "long_name": "Plasma potential relative to RPA ground",
    },
    {
        "name": "first_electron_temperature",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x * 10.0,
        "units": "K",
        "long_name": "First electron temperature",
    },
    {
        "name": "first_electron_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "First electron density",
    },
    {
        "name": "first_plasma_potential_relative_to_spacecraft_ground",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(6.0 - (x / 10.0), 1),
        "units": "V",
        "long_name": "First plasma potential relative to spacecraft ground",
    },
    {
        "name": "second_electron_temperature",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x * 10.0,
        "units": "K",
        "long_name": "Second electron temperature",
    },
    {
        "name": "second_electron_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "Second electron density",
    },
    {
        "name": "second_plasma_potential_relative_to_spacecraft_ground",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(6.0 - (x / 10.0), 1),
        "units": "V",
        "long_name": "Second plasma potential relative to spacecraft ground",
    },
    {
        "name": "zero_fill",
        "size": 3,
        "type": "bytes",
        "transform": lambda x: x,
        "units": None,
        "long_name": "Zero fill",
    },
]