RPA_SCHEMA = [
    {
        "name": "second_of_minute",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "second",
        "long_name": "Second of minute",
    },
    {
        "name": "ion_temperature",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "K",
        "long_name": "Ion temperature",
    },
    {
        "name": "ram_ion_drift_speed",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Ram ion drift speed",
    },
    {
        "name": "spacecraft_potential_relative_to_plasma",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 35.0, 1),
        "units": "V",
        "long_name": "Spacecraft potential relative to plasma",
    },
    {
        "name": "num_ion_species",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "count",
        "long_name": "Number of ion species",
    },
    {
        "name": "ion_species1_mass",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "AMU",
        "long_name": "Mass of 1st ion species",
    },
    {
        "name": "ion_species1_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "Density of 1st ion species",
    },
    {
        "name": "ion_species2_mass",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "AMU",
        "long_name": "Mass of 2nd ion species",
    },
    {
        "name": "ion_species2_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "Density of 2nd ion species",
    },
    {
        "name": "ion_species3_mass",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "AMU",
        "long_name": "Mass of 3rd ion species",
    },
    {
        "name": "ion_species3_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "Density of 3rd ion species",
    },
    {
        "name": "ion_species4_mass",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "AMU",
        "long_name": "Mass of 4th ion species",
    },
    {
        "name": "ion_species4_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "Density of 4th ion species",
    },
    {
        "name": "error_estimate",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "Error estimate",
    },
    {
        "name": "total_ion_density_saturation",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "Total ion density from saturation current",
    },
    {
        "name": "std_dev_total_ion_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "Standard deviation of total ion density",
    },
    {
        "name": "zero_fill",
        "size": 2,
        "type": "bytes",
        "transform": lambda x: x,
        "units": None,
        "long_name": "Zero fill",
    },
]