SM_SCHEMA = [
    {
        "name": "second_of_minute",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "second",
        "long_name": "Second of minute",
    },
    {
        "name": "filter1",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "1st filter value",
    },
    {
        "name": "filter2",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "2nd filter value",
    },
    {
        "name": "filter3",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "3rd filter value",
    },
    {
        "name": "filter4",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "4th filter value",
    },
    {
        "name": "filter5",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "5th filter value",
    },
    {
        "name": "filter6",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "6th filter value",
    },
    {
        "name": "filter7",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "7th filter value",
    },
    {
        "name": "filter8",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "8th filter value",
    },
    {
        "name": "filter9",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "9th filter value",
    },
    {
        "name": "ion_density_1sec_avg",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 10000.0),
        "units": "cm-3",
        "long_name": "1-sec average of ion density",
    },
    {
        "name": "ion_density_variance",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 10000.0),
        "units": "cm-3",
        "long_name": "Variance of ion density",
    },
    {
        "name": "zero_fill",
        "size": 9,
        "type": "bytes",
        "transform": lambda x: x,
        "units": None,
        "long_name": "Zero fill",
    },
]