HEADER_SCHEMA = [
    {
        "name": "spacecraft_id",
        "size": 5,
        "type": "ascii",
        "transform": lambda x: x.strip(),
        "units": None,
        "long_name": "Spacecraft ID",
    },
    {
        "name": "data_file_id",
        "size": 6,
        "type": "ascii",
        "transform": lambda x: x.strip(),
        "units": None,
        "long_name": "Data file ID",
    },
    {
        "name": "year",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x + 1950,
        "units": "year",
        "long_name": "Year",
    },
    {
        "name": "day_of_year",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x,
        "units": "day",
        "long_name": "Day of year",
    },
    {
        "name": "hour",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "hour",
        "long_name": "Hour of day",
    },
    {
        "name": "minute_of_hour",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "minute",
        "long_name": "Minute of hour",
    },
    {
        "name": "geodetic_latitude",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
        "units": "degrees_north",
        "long_name": "Geodetic latitude",
    },
    {
        "name": "geographic_longitude",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees_east",
        "long_name": "Geographic longitude",
    },
    {
        "name": "geomagnetic_latitude_subsat",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
        "units": "degrees",
        "long_name": "Geomagnetic latitude at sub-satellite point",
    },
    {
        "name": "mlt_110km_intercept",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "hours",
        "long_name": "Magnetic local time at 110 km field line intercept",
    },
    {
        "name": "geomagnetic_longitude_subsat",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees",
        "long_name": "Geomagnetic longitude at sub-satellite point",
    },
    {
        "name": "geographic_latitude_subsolar",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
        "units": "degrees_north",
        "long_name": "Geographic latitude of sub-solar point",
    },
    {
        "name": "geographic_longitude_subsolar",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees_east",
        "long_name": "Geographic longitude of sub-solar point",
    },
    {
        "name": "geographic_latitude_110km",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
        "units": "degrees_north",
        "long_name": "Geographic latitude at 110 km altitude on the same magnetic field line as the spacecraft",
    },
    {
        "name": "geographic_longitude_110km",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees_east",
        "long_name": "Geographic longitude at 110 km altitude on the same magnetic field line as the spacecraft",
    },
    {
        "name": "corrected_geomagnetic_latitude_110km",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
        "units": "degrees",
        "long_name": "Corrected geomagnetic latitude at 110 km altitude",
    },
    {
        "name": "corrected_geomagnetic_longitude_110km",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees",
        "long_name": "Corrected geomagnetic longitude at 110 km altitude",
    },
    {
        "name": "invariant_latitude",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees",
        "long_name": "Invariant latitude",
    },
    {
        "name": "altitude_start_minute",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x,
        "units": "nmi",
        "long_name": "Altitude at the start of the minute",
    },
    {
        "name": "altitude_end_minute",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x,
        "units": "nmi",
        "long_name": "Altitude at the end of the minute",
    },
    {
        "name": "model_magnetic_north",
        "size": 4,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 70000.0, 1),
        "units": "nT",
        "long_name": "Northward component of model magnetic field at the satellite",
    },
    {
        "name": "model_magnetic_east",
        "size": 4,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 70000.0, 1),
        "units": "nT",
        "long_name": "Eastward component of model magnetic field at the satellite",
    },
    {
        "name": "model_magnetic_down",
        "size": 4,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 70000.0, 1),
        "units": "nT",
        "long_name": "Downward component of model magnetic field at the satellite",
    },
    {
        "name": "satellite_pos_x",
        "size": 3,
        "type": "uint",
        "transform": lambda x: round((x / 100000.0) - 1.0, 1),
        "units": "1",
        "long_name": "Geographic x-component of satellite position unit vector",
    },
    {
        "name": "satellite_pos_y",
        "size": 3,
        "type": "uint",
        "transform": lambda x: round((x / 100000.0) - 1.0, 1),
        "units": "1",
        "long_name": "Geographic y-component of satellite position unit vector",
    },
    {
        "name": "satellite_pos_z",
        "size": 3,
        "type": "uint",
        "transform": lambda x: round((x / 100000.0) - 1.0, 1),
        "units": "1",
        "long_name": "Geographic z-component of satellite position unit vector",
    },
    {
        "name": "potential_control_flag",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "1",
        "long_name": "Potential control model flag",
    },
    {
        "name": "spacecraft_electron_probe_ground_potential",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x - 10,
        "units": "V",
        "long_name": "Potential difference between spacecraft and electron probe ground",
    },
    {
        "name": "ion_array_electron_probe_ground_potential",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x - 3,
        "units": "V",
        "long_name": "Potential difference between ion array and electron probe ground",
    },
    {
        "name": "repeller_grid_functions",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "1",
        "long_name": "Drift meter repeller grid functions",
    },
    {
        "name": "scintillation_filter_commands",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "1",
        "long_name": "Scintillation meter filter range commands",
    },
    {
        "name": "seconds_in_minute",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "count",
        "long_name": "Number of seconds of data for this minute",
    },
]


DM_SCHEMA = [
    {
        "name": "second_of_minute",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "second",
        "long_name": "Second of minute",
    },
    {
        "name": "vertical_speed_1",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Vertical speed, 1st sample of second",
    },
    {
        "name": "vertical_speed_2",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Vertical speed, 2nd sample of second",
    },
    {
        "name": "vertical_speed_3",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Vertical speed, 3rd sample of second",
    },
    {
        "name": "vertical_speed_4",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Vertical speed, 4th sample of second",
    },
    {
        "name": "vertical_speed_5",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Vertical speed, 5th sample of second",
    },
    {
        "name": "vertical_speed_6",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Vertical speed, 6th sample of second",
    },
    {
        "name": "horizontal_speed_1",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Horizontal speed, 1st sample of second",
    },
    {
        "name": "horizontal_speed_2",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Horizontal speed, 2nd sample of second",
    },
    {
        "name": "horizontal_speed_3",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Horizontal speed, 3rd sample of second",
    },
    {
        "name": "horizontal_speed_4",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Horizontal speed, 4th sample of second",
    },
    {
        "name": "horizontal_speed_5",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Horizontal speed, 5th sample of second",
    },
    {
        "name": "horizontal_speed_6",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Horizontal speed, 6th sample of second",
    },
    {
        "name": "lla_llb_ratio",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x,
        "units": "1",
        "long_name": "Ratio of LLA to LLB or H+ mode indicator",
    },
    {
        "name": "measured_aperture_potential",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 100.0) - 19.0, 1),
        "units": "V",
        "long_name": "Measured aperture potential",
    },
    {
        "name": "zero_fill",
        "size": 8,
        "type": "bytes",
        "transform": lambda x: x,
        "units": None,
        "long_name": "Zero fill",
    },
]

HEADER_SCHEMA_2 = [
    {
        "name": "spacecraft_id",
        "size": 5,
        "type": "ascii",
        "transform": lambda x: x.strip(),
        "units": None,
        "long_name": "Spacecraft ID",
    },
    {
        "name": "data_file_id",
        "size": 6,
        "type": "ascii",
        "transform": lambda x: x.strip(),
        "units": None,
        "long_name": "Data file ID",
    },
    {
        "name": "year",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x + 1950,
        "units": "year",
        "long_name": "Year",
    },
    {
        "name": "day_of_year",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x,
        "units": "day",
        "long_name": "Day of year",
    },
    {
        "name": "hour",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "hour",
        "long_name": "Hour of day",
    },
    {
        "name": "minute_of_hour",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "minute",
        "long_name": "Minute of hour",
    },
    {
        "name": "geodetic_latitude",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
        "units": "degrees_north",
        "long_name": "Geodetic latitude",
    },
    {
        "name": "geographic_longitude",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees_east",
        "long_name": "Geographic longitude",
    },
    {
        "name": "geomagnetic_latitude_subsat",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
        "units": "degrees",
        "long_name": "Geomagnetic latitude at sub-satellite point",
    },
    {
        "name": "mlt_110km_intercept",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "hours",
        "long_name": "Magnetic local time at 110 km field line intercept",
    },
    {
        "name": "geomagnetic_longitude_subsat",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees",
        "long_name": "Geomagnetic longitude at sub-satellite point",
    },
    {
        "name": "geographic_latitude_subsolar",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
        "units": "degrees_north",
        "long_name": "Geographic latitude of sub-solar point",
    },
    {
        "name": "geographic_longitude_subsolar",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees_east",
        "long_name": "Geographic longitude of sub-solar point",
    },
    {
        "name": "geographic_latitude_110km",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
        "units": "degrees_north",
        "long_name": "Geographic latitude at 110 km altitude on the same magnetic field line as the spacecraft",
    },
    {
        "name": "geographic_longitude_110km",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees_east",
        "long_name": "Geographic longitude at 110 km altitude on the same magnetic field line as the spacecraft",
    },
    {
        "name": "corrected_geomagnetic_latitude_110km",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
        "units": "degrees",
        "long_name": "Corrected geomagnetic latitude at 110 km altitude",
    },
    {
        "name": "corrected_geomagnetic_longitude_110km",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees",
        "long_name": "Corrected geomagnetic longitude at 110 km altitude",
    },
    {
        "name": "invariant_latitude",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
        "units": "degrees",
        "long_name": "Invariant latitude",
    },
    {
        "name": "altitude_start_minute",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x,
        "units": "nmi",
        "long_name": "Altitude at the start of the minute",
    },
    {
        "name": "altitude_end_minute",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x,
        "units": "nmi",
        "long_name": "Altitude at the end of the minute",
    },
    {
        "name": "model_magnetic_north",
        "size": 4,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 70000.0, 1),
        "units": "nT",
        "long_name": "Northward component of model magnetic field at the satellite",
    },
    {
        "name": "model_magnetic_east",
        "size": 4,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 70000.0, 1),
        "units": "nT",
        "long_name": "Eastward component of model magnetic field at the satellite",
    },
    {
        "name": "model_magnetic_down",
        "size": 4,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 70000.0, 1),
        "units": "nT",
        "long_name": "Downward component of model magnetic field at the satellite",
    },
    {
        "name": "satellite_pos_x",
        "size": 3,
        "type": "uint",
        "transform": lambda x: round((x / 100000.0) - 1.0, 1),
        "units": "1",
        "long_name": "Geographic x-component of satellite position unit vector",
    },
    {
        "name": "satellite_pos_y",
        "size": 3,
        "type": "uint",
        "transform": lambda x: round((x / 100000.0) - 1.0, 1),
        "units": "1",
        "long_name": "Geographic y-component of satellite position unit vector",
    },
    {
        "name": "satellite_pos_z",
        "size": 3,
        "type": "uint",
        "transform": lambda x: round((x / 100000.0) - 1.0, 1),
        "units": "1",
        "long_name": "Geographic z-component of satellite position unit vector",
    },
    {
        "name": "potential_control_flag",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "1",
        "long_name": "Potential control model flag",
    },
    {
        "name": "spacecraft_electron_probe_ground_potential",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x - 10,
        "units": "V",
        "long_name": "Potential difference between spacecraft and electron probe ground",
    },
    {
        "name": "ion_array_electron_probe_ground_potential",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x - 3,
        "units": "V",
        "long_name": "Potential difference between ion array and electron probe ground",
    },
    {
        "name": "repeller_grid_functions",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "1",
        "long_name": "Drift meter repeller grid functions",
    },
    {
        "name": "scintillation_filter_commands",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "1",
        "long_name": "Scintillation meter filter range commands",
    },
    {
        "name": "number_set",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "count",
        "long_name": "Number of outputs for this minute",
    },
]


MP_SCHEMA = [
    {
        "name": "second_of_minute",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "second",
        "long_name": "Second of minute for the set of data",
    },
    {
        "name": "ram_ion_drift_speed",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Ram ion drift speed",
    },
    {
        "name": "o_plus_ion_temperature",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x * 10.0,
        "units": "K",
        "long_name": "O+ ion temperature",
    },
    {
        "name": "h_plus_ion_temperature",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x * 10.0,
        "units": "K",
        "long_name": "H+ ion temperature",
    },
    {
        "name": "o_plus_ion_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "O+ ion density",
    },
    {
        "name": "h_plus_ion_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "H+ ion density",
    },
    {
        "name": "plasma_potential_relative_to_rpa_ground",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 100.0) - 6.0, 1),
        "units": "V",
        "long_name": "Plasma potential relative to RPA ground",
    },
    {
        "name": "first_electron_temperature",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x * 10.0,
        "units": "K",
        "long_name": "First electron temperature",
    },
    {
        "name": "first_electron_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "First electron density",
    },
    {
        "name": "first_plasma_potential_relative_to_spacecraft_ground",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(6.0 - (x / 10.0), 1),
        "units": "V",
        "long_name": "First plasma potential relative to spacecraft ground",
    },
    {
        "name": "second_electron_temperature",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x * 10.0,
        "units": "K",
        "long_name": "Second electron temperature",
    },
    {
        "name": "second_electron_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "Second electron density",
    },
    {
        "name": "second_plasma_potential_relative_to_spacecraft_ground",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(6.0 - (x / 10.0), 1),
        "units": "V",
        "long_name": "Second plasma potential relative to spacecraft ground",
    },
    {
        "name": "zero_fill",
        "size": 3,
        "type": "bytes",
        "transform": lambda x: x,
        "units": None,
        "long_name": "Zero fill",
    },
]

RPA_SCHEMA = [
    {
        "name": "second_of_minute",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "second",
        "long_name": "Second of minute",
    },
    {
        "name": "ion_temperature",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "K",
        "long_name": "Ion temperature",
    },
    {
        "name": "ram_ion_drift_speed",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
        "units": "m/s",
        "long_name": "Ram ion drift speed",
    },
    {
        "name": "spacecraft_potential_relative_to_plasma",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 35.0, 1),
        "units": "V",
        "long_name": "Spacecraft potential relative to plasma",
    },
    {
        "name": "num_ion_species",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "count",
        "long_name": "Number of ion species",
    },
    {
        "name": "ion_species1_mass",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "AMU",
        "long_name": "Mass of 1st ion species",
    },
    {
        "name": "ion_species1_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "Density of 1st ion species",
    },
    {
        "name": "ion_species2_mass",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "AMU",
        "long_name": "Mass of 2nd ion species",
    },
    {
        "name": "ion_species2_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "Density of 2nd ion species",
    },
    {
        "name": "ion_species3_mass",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "AMU",
        "long_name": "Mass of 3rd ion species",
    },
    {
        "name": "ion_species3_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "Density of 3rd ion species",
    },
    {
        "name": "ion_species4_mass",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "AMU",
        "long_name": "Mass of 4th ion species",
    },
    {
        "name": "ion_species4_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "Density of 4th ion species",
    },
    {
        "name": "error_estimate",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "Error estimate",
    },
    {
        "name": "total_ion_density_saturation",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "Total ion density from saturation current",
    },
    {
        "name": "std_dev_total_ion_density",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 100.0),
        "units": "cm-3",
        "long_name": "Standard deviation of total ion density",
    },
    {
        "name": "zero_fill",
        "size": 2,
        "type": "bytes",
        "transform": lambda x: x,
        "units": None,
        "long_name": "Zero fill",
    },
]


SM_SCHEMA = [
    {
        "name": "second_of_minute",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
        "units": "second",
        "long_name": "Second of minute",
    },
    {
        "name": "filter1",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "1st filter value",
    },
    {
        "name": "filter2",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "2nd filter value",
    },
    {
        "name": "filter3",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "3rd filter value",
    },
    {
        "name": "filter4",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "4th filter value",
    },
    {
        "name": "filter5",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "5th filter value",
    },
    {
        "name": "filter6",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "6th filter value",
    },
    {
        "name": "filter7",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "7th filter value",
    },
    {
        "name": "filter8",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "8th filter value",
    },
    {
        "name": "filter9",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 1000.0),
        "units": "cm-3",
        "long_name": "9th filter value",
    },
    {
        "name": "ion_density_1sec_avg",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 10000.0),
        "units": "cm-3",
        "long_name": "1-sec average of ion density",
    },
    {
        "name": "ion_density_variance",
        "size": 2,
        "type": "uint",
        "transform": lambda x: 10 ** (x / 10000.0),
        "units": "cm-3",
        "long_name": "Variance of ion density",
    },
    {
        "name": "zero_fill",
        "size": 9,
        "type": "bytes",
        "transform": lambda x: x,
        "units": None,
        "long_name": "Zero fill",
    },
]