HEADER_SCHEMA = [
    {
        "name": "spacecraft_id",
        "size": 5,
        "type": "ascii",
        "transform": lambda x: x.strip(),
    },
    {
        "name": "data_file_id",
        "size": 6,
        "type": "ascii",
        "transform": lambda x: x.strip(),
    },
    {
        "name": "year",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x + 1950,
    },
    {
        "name": "day_of_year",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x,
    },
    {
        "name": "hour",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
    },
    {
        "name": "minute",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
    },
    {
        "name": "geodetic_latitude",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
    },
    {
        "name": "geographic_longitude",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
    },
    {
        "name": "geomagnetic_latitude_subsat",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
    },
    {
        "name": "mlt_110km_intercept",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
    },
    {
        "name": "geomagnetic_longitude_subsat",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
    },
    {
        "name": "geographic_latitude_subsolar",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
    },
    {
        "name": "geographic_longitude_subsolar",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
    },
    {
        "name": "geographic_latitude_110km",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
    },
    {
        "name": "geographic_longitude_110km",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
    },
    {
        "name": "corrected_geomagnetic_latitude_110km",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 90.0, 1),
    },
    {
        "name": "corrected_geomagnetic_longitude_110km",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
    },
    {
        "name": "invariant_latitude",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round(x / 10.0, 1),
    },
    {
        "name": "altitude_start_minute",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x,
    },
    {
        "name": "altitude_end_minute",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x,
    },
    {
        "name": "model_magnetic_north",
        "size": 4,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 70000.0, 1),
    },
    {
        "name": "model_magnetic_east",
        "size": 4,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 70000.0, 1),
    },
    {
        "name": "model_magnetic_down",
        "size": 4,
        "type": "uint",
        "transform": lambda x: round((x / 10.0) - 70000.0, 1),
    },
    {
        "name": "satellite_pos_x",
        "size": 3,
        "type": "uint",
        "transform": lambda x: round((x / 100000.0) - 1.0, 1),
    },
    {
        "name": "satellite_pos_y",
        "size": 3,
        "type": "uint",
        "transform": lambda x: round((x / 100000.0) - 1.0, 1),
    },
    {
        "name": "satellite_pos_z",
        "size": 3,
        "type": "uint",
        "transform": lambda x: round((x / 100000.0) - 1.0, 1),
    },
    {
        "name": "potential_control_flag",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
    },
    {
        "name": "spacecraft_electron_probe_ground_potential",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x - 10,
    },
    {
        "name": "ion_array_electron_probe_ground_potential",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x - 3,
    },
    {
        "name": "repeller_grid_functions",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
    },
    {
        "name": "scintillation_filter_commands",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
    },
    {
        "name": "seconds_in_minute",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
    },
]


DM_SCHEMA = [
    {
        "name": "second_of_minute",
        "size": 1,
        "type": "uint",
        "transform": lambda x: x,
    },
    {
        "name": "vertical_speed_1",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
    },
    {
        "name": "vertical_speed_2",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
    },
    {
        "name": "vertical_speed_3",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
    },
    {
        "name": "vertical_speed_4",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
    },
    {
        "name": "vertical_speed_5",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
    },
    {
        "name": "vertical_speed_6",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
    },
    {
        "name": "horizontal_speed_1",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
    },
    {
        "name": "horizontal_speed_2",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
    },
    {
        "name": "horizontal_speed_3",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
    },
    {
        "name": "horizontal_speed_4",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
    },
    {
        "name": "horizontal_speed_5",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
    },
    {
        "name": "horizontal_speed_6",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((10.0 * x) - 3000.0, 1),
    },
    {
        "name": "lla_llb_ratio",
        "size": 2,
        "type": "uint",
        "transform": lambda x: x,
    },
    {
        "name": "measured_aperture_potential",
        "size": 2,
        "type": "uint",
        "transform": lambda x: round((x / 100.0) - 19.0, 1),
    },
    {
        "name": "zero_fill",
        "size": 8,
        "type": "bytes",
        "transform": lambda x: x,
    },
]